### ISSUE TITLE
텍스트 뷰 높이 고정: 입력 가능한 글자 수 제한 or 다른 방법?

### ISSUE THREAD

**Issue by oosgnak** [oreyo/Project_Oreo#13]
* 텍스트 뷰에 입력 가능한 글자 수 제한하는 방법
  * func textView(UITextView, shouldChangeTextIn: NSRange, replacementText: String) 이후 텍스트 변경할지 말지 적용
* 글자 수 제한하더라도 글자마다 폭이 달라서, 폭이 큰 글자로만 채우면 텍스트 뷰 높이를 초과하는 문제

**Comment by jjy4880** [comment]
```swift
