### ISSUE TITLE
초기단계 고민거리

### ISSUE THREAD

**Issue by jjy4880** [oreyo/Project_Oreo#5]
Q. DB에 저장할 때는 image_url,thumb_url 사용하고 이미지 편집이나 필터에는 PHAsset을 사용하는지.. 잘 모르겠다. PHAsset을 어떤식으로 사용해야할지.

A.
* UIimage를 data 변환, 그리고 write
  * data: 로컬 document directory에 저장
  * data의 url: DB에 저장
* 기본 이미지와 썸네일 이미지를 별도의 디렉터리에 보관

**Comment by jjy4880** [comment]
Q. Storyboard를 Reference로 연결하여 테스트 해 보았는데 이방법이 올바른 방법인지 확인질문!

**Comment by jjy4880** [comment]
Q. 프로젝트 시작할 때 전체적인 스토리보드 UI, 화면전환기능 등 전체적인 사항들을 미리 작성하고 세부기능들을 구현하는 방법이 좋은지, 시작부분만 설정해놓고 생성해 나가면서 추가하는 방법이 좋은지.
A.

**Comment by oosgnak** [comment]
Q. 스토리보드 사용하는 프로젝트에서 gitignore 파일로 제외해줘야할 것들에는 또 무엇이 있는지?

**Comment by oosgnak** [comment]
Q. gitignore 파일에 xcode 관련 파일들 설정하면, 다른 곳에서 이 리포지터리를 클론했을 때 구동이 잘 되는지 점검. 프로젝트 파일 손상 없는지.

**Comment by oosgnak** [comment]
* 비동기 작업으로 해야할 것!
  * diskio 또는 fileio의 쓰기, 읽기 작업
  * 필터 미리보기: 여러 개의 미리보기들이 모두 로드될 때까지 기다리는 것이 아니라, 미리 온 것부터 보여주도록. 아직 오지 않은 것들은 액티비티 인디케이터 같은 걸로 사용자에게 알려주기.
    * 또는 필터를 적용한 샘플이미지를 나열하여 보여주기.
