### ISSUE TITLE
Message from debugger: Terminated due to signal 9

### ISSUE THREAD

**Issue by oosgnak** [oreyo/Project_Oreo#82]
1. 앱 최초 실행 후 이미지 피커가 요청하는 권한에 거절한 뒤
2. 설정으로 이동하도록 유도하는 alert를 통해 설정으로 이동한 뒤
3. 사진 권한 켜주면 Message from debugger: Terminated due to signal 9 뜨면서 디버깅 강제 종료

**Comment by jjy4880** [comment]
계속 발생하나요?
